---
apiVersion: v1
kind: Service
metadata:
  name: mysql-primary  ### used this name becuase I will not have to change in application.properties
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None # Headless service
  selector:
    app: mysql
...
