trigger:
- none

pr: none
pool: 
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: MySQLDeployment
  displayName: MySQLDeployment
  jobs:
  - deployment: MySQLDeployment
    displayName: MySQLDeployment
    environment: "stage"
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'Azure DevOps Service Connection'
              azureResourceGroup: 'bankapp-rg'
              kubernetesCluster: 'bankapp-cluster'
              namespace: 'mysql'
              command: 'apply'
              arguments: '-k $(System.DefaultWorkingDirectory)/overlay/mysql'
              containerRegistryType: 'Azure Container Registry'
