trigger:
- none

pr: none
pool: 
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: MySQLDeployment
  displayName: MySQLDeployment
  jobs:
  - deployment: MySQLDeployment
    displayName: MySQLDeployment
    environment: "stage"
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'Azure DevOps Service Connection'
              azureResourceGroup: 'bankapp-rg'
              kubernetesCluster: 'bankapp-cluster'
              namespace: 'mysql'
              manifests: 'overlay/mysql/kustomization.yaml'
