---
# Java Based Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp
        image: 027330342406.dkr.ecr.us-east-2.amazonaws.com/bankapp:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
...

