---
# Java Based Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp
        image: bankappcontainer24registry.azurecr.io/samplewebapp:1.0.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "256m"
          limits:
            memory: "256Mi"
            cpu: "512m"
        imagePullPolicy: Always
        securityContext:
          privileged: false                # Container does not have full root privileges on the host system
          allowPrivilegeEscalation: false  # Prevents processes within the container from gaining more privileges than their parent process
      imagePullSecrets:
      - name: bankapp-auth
...

